apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hydrosense-iot

resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - storage.yaml
  - mosquitto.yaml
  - influxdb.yaml
  - telegraf.yaml
  - grafana.yaml
  - simulator-nodes.yaml
