apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
  namespace: hydrosense-iot
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "adminpassword123"
  admin-org: "hydrosense"
  admin-bucket: "river_water_quality"
  admin-token: "hydrosense-super-secret-auth-token-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: hydrosense-iot
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "admin"
